services:
  teslo_shop_pg_db:
    image: postgres:14-alpine3.22
    container_name: pg_teslo_shop
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/teslo_shop_postgresql/data
